name: cdm_vip
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  awesome_dialog: ^2.2.1
  shared_preferences: ^2.0.15
  google_fonts: ^2.3.3
  url_launcher: ^6.1.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  rename: ^2.0.1
  provider: ^6.0.3
  device_info_plus: ^3.2.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "images/CDM.jpg"
  
  flutter_lints: ^2.0.0

flutter:

  generate: true
  uses-material-design: true
  
  assets:
    - images/
